language: node_js
node_js:
- '10'
sudo: false
install:
- npm install --only=dev
- npm ci
before_script:
- node node_modules/eslint/bin/eslint.js .
script:
- node ./edenconfig.js
after_script:
- npm test
deploy:
  provider: npm
  email: alex@edenup.com
  api_key:
    secure: YfERcrJ5vmUjb4I4jYh/5PYVsIDnKKX8X04l7UWSzKSsUXbvsNtKo5Bg32IaEmlNSKs51i6GNG1SaaYJ1uaKfl8C3pA1p+zn0nwYL9m8ruMw1Mu61V72cHOdi1q6u/04sIEqX/7W2CZrG/tZGRK3ofR3jOdywKnr+i1IAiTLY9on5yL0JoZ4HlrLRdx18NUzgvWb0glC5WkElEzDJRlEylSipKnP2S6OUuqW+yLyTZvOxN+JEuamkfM88A7stGVgnLrDiPq8Q56lGosigBK/PcikTG+JoDMOOgmfGwBuRDGmEn7yOYH/5QDYdKe300dBi9x6gwDvi1phHyrHfiQKpaJGo/7cKzyMBlekxSenNX/vd0OnTW22ZqHUCmiybPe95+XhiZNcrDhU3OgxLUQi56E4J5w5EjbavmEm+DzqEm4nNLrC5jBx+Sv6uK+VUU+w3Vg3netawnG9M59O5cDoACUbcJEImNfSXa5voAUN9raQpBIshBcegh3NEshGCLq8B2vqcoYjszjv+WUWeOSswytLWu3BlxL8GqZPIYALj3jcUzTlK430H3n4octpl7G/fqogJIUtWsazwVCerfeSWm8H1xB3RGqHm9cAbpi/eVdu9tGn0PG/ml0zqn9jgla9iPNGMs3vbqeZPER4LKiEGbBmPpQrMPtxMwMnJHaknDI=
  on:
    tags: true
    repo: ifactorydigital/ifactoryjs_asset
